---
title: "Tarea2 Métodos Numéricos"
author: "Guillermina Montanari"
date: "2/10/2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Tarea 2

Considera el siguiente programa:

```
#include <stdio.h>
main(void){
    int c;
    c = getchar();
    while( c != EOF){
        putchar(c);
        c = getchar();   
    } 
}
```

Si lo ejecutas, para salir del programa utiliza `ctrl + c`

1) Investiga lo que quieren decir las letras `EOF`. ¿Por qué se debe definir c como `int`?
    - EOF significa End Of File
    - La función getchar() lee el siguiente caracter que se ingrese en el input - en este caso es el teclado -, y lo devuelve al usuario. Esta función devuelve un número entero, que es el código ASCII del caracter ingresado, y por eso la variable **c** debe ser definida como **int**.



2) Modifica `main` para que sólo se llame una vez a la función `getchar()`

```
#include <stdio.h>
main(void){
    int c;
    while( (c = getchar()) != EOF){
        putchar(c);   
    } 
}
```



3) Utiliza `getchar` para escribir un programa que cuente el número de caracteres dado un `stdin` e imprima este número. Al dar enter (salto de línea) el programa termina. Por ejemplo:

```

$echo -e "hola\n" | ./ejecutable.out

```

entonces el programa imprime `4`

```

#include <stdio.h>
main(void){
    int c,n=0;
    while( (c = getchar()) != '\n'){
        n++;
    }
    printf("Cantidad de letras : %d\n", n-1); 
}

```

4) Modifica el programa de 3) para que cuente el número de líneas dado un archivo de `stdin`:

```
./ejecutable.out < archivo.txt
```

De manera individual cada persona haga un directorio con su clave y coloquen ahí sus resultados.

```
#include <stdio.h>
main(void){
    int c,n=0;
    while( c != EOF){
        c = getchar();
        n++;
    }
    printf("Cantidad de lineas : %d\n", n-1); 
}


Se entrega el lunes 13 de febrero.
