---
title: "Examen Parcial 2"
author: "Amaury Gutiérrez"
date: "3/8/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

## 1.1

1. ¿Cuáles  son las características del análisis    numérico    y   cómputo científico?

El cómputo científico se encarga del desarrollo, la implementación y el uso de algoritmos númericos para aplicaciones en el análisis y ajuste de modelos, optimización, machine learning entre otros. El análisis numérico se encarga del diseño y análisis de algoritmos que surgen en la computación o la ingeniería. Usualemnte los problemas se desarrollan en el mundo real donde las cantidades son continuas. A través de procesos iterativos, se puede llegar a aproximaciones que son útiles en la prática.

2. ¿Qué propiedades debe    tener   un  algoritmo   "bueno"?

Un buen algoritmo debe ser eficiente, confiable y exacto, estable. Eficiencia se refiere al costo computacional, la estabilidad se refiere a que pequeños cambios en los datos de entrada deben causar pequeñas cambios en los resultados del algoritmo.

3. ¿Cuáles fuentes de  error principalmente  son estudiadas  por el  análisis    numérico y cómputo científico  al  resolver  un  problema?

Truncamiento, que se relaciona con el uso de cantidades finitas.

Redondeo, relacionado con la aritmética que usa la computadora y la forma en la que representa los números.

4. Menciona las diferencias entre   los términos    inexactitud y   precisión

La exactitud es que tan cercano se encuentra un valor calculado con respecto al valor real. La precisión es que tan cercanos se encuentran los valores calculados entre si.

## 1.2

1) ¿Cuáles  componentes definen  a   un  sistema de  punto   flotante?
2) Si   un  número  tiene   una representación  exacta  en  la  máquina,    ¿qué  nombre  recibe?

A los números  que tienen una representación exacta en $\mathbb{F}\ell$ se les conoce como números máquina.

3) ¿Qué es  un  sistema de  punto   flotante    normalizado?

En un sistema de punto flotante normalizado, se exige que el primer dígito de la mantisa sea distinto de $0$.

4) Menciona algunas propiedades de  un  sistema de  punto   flotante    normalizado.

En un sistema de punto flotante normalizado cada número tiene una representación única. El único número que puede tener $0$ en toda la mantisa es el $0$.

5) ¿Cuántos bits    se  utilizan    en  el  hardware    de  una máquina para    almacenar   un número  en  un  sistema de  doble   precisión?

En un sistema de punto flotante de doble precisión se utilizan $64$ bits para representar un número. Se usa $1$ bit para el signo, $11$ bits para el exponente y $52$ bits para la mantisa.

6) ¿Qué nombre  reciben los errores que se  generan por utilizar    un  sistema de  punto flotante?

Se les conoce como errores por redondeo.

7) ¿Cuáles reglas utiliza la máquina para dar aproximaciones a un número?

Existen dos tipos de reglas, regla de corte donde se trunca la mantisa para asignar, a cada número real, el número en el sistema de punto flotante. El error máximo será entonces el épsilon de la máquina. La regla por redondeo, le asigna el número más cercano a la última posición de la mantisa.

8) Explica  con palabras    la  diferencia  entre   el  epsilon de  la  máquina y el  nivel de  underflow:
  a. ¿Cuál de ellos depende únicamente del número de dígitos de la mantisa?
  b. ¿Cuál de ellos depende únicamente del número de dígitos del exponente?
  c. ¿Cuál de ellos no depende de la regla usada que se cuestionó en la pregunta $7$?
  
9) Si calculamos un error relativo para una aproximación y resulta ser del orden de 10^(-8) ¿alrededor de cuántos dígitos correctos tengo  en mi aproximación?

El error relativo nos ayuda a determinar el número de dígitos significativos que tiene una aproximación, si el Error relativo es del orden de $10^{-8}$ entonces tenemos alrededir de 8 dígitos correctos.

10) Menciona algunos problemas típicos de la aritmética de máquina y algunas formas de resolverlos.

Pérdida de cifras significativas por la resta de números similares.

Suma de un número de magnitud grande con un númerod e magnitud pequeña.
Términos  de una suma cuya magnitud de máyor que la suma misma por ejemplo en sumas que involucren términos con signos alternados.
Multiplicación por un número de magnitud grande.
División entre un número de magnitud pequeña.

Soluciones:
Usar mayor precisión
Reordenar operaciones
Escalar el problema
Estandarizar variables

## 1.3
1) ¿Qué factores    influyen    en  la  falta   de  exactitud   de  un  cálculo?

La condición de un problema adicional a la estabilidad de un algoritmo. Podemos tener un algoritmo estable con un problema mal condicionado o un algoritmo inestable con un problema bien condicionado y en ambos casos encontraremos inexactitud.

2) Menciona 5   propiedades que un  conjunto    debe    cumplir para    que sea considerado un  espacio vectorial.

- $x + y = y + x$  Conmutatividad
- $x + (y + z) = (x + y) + z$ Asociatividad
- $x + 0 = x$ Neutro
- $x -x = 0$ Inverso
- $a(bx) = (ab) x$ Asociatividad
- $1(x) = x$ Neutro
- $a\dot(x+y) = ax +ay$
- $(a + b)\dot x = ax +bx$

3) Menciona las propiedades que debe    cumplir una función para    que se  considere una norma.

- $p(ax) = |a|p(x)$
- $p(x + y) \le p(x) + p(y)$
- $p(x) = 0$ entonces $x$ es el vector $0$

4) ¿Qué es una norma matricial inducida?, ¿qué mide una norma matricial inducida?

Una norma matricial inducida es una norma para el espacio de matrices de $m\times n$, se define como:

$$
||A||_{(m,n)}=\sup_{x\in \mathbb{R}^n}\frac{||A||_m}{||x||_n}
$$


5) ¿La  norma   de  Frobenius,  es  una norma   matricial   inducida?

No, la norma de Frobenius es una norma matricial que no es inducida por ninguna norma vectorial.

6) ¿A   qué son iguales $\sup(\emptyset)$, $\inf(\emptyset)$?

Por convención $\sup(\emptyset) = -\infty$, $\inf(\emptyset) = \infty$

7) Si   f   es  un  problema    mal condicionado,   ¿a  qué nos referimos?

La condición de un problema se refiere a como resultan afectados las salidas de un problema en relación con las entradas. Si pequeñas variaciones en los datos de entrada producen pequeás alteraciones en el espacio de salida, decimos que el problema es bien condicionado. Por otro lado si pequeñas variaciones en los datos de entrada producen grandes variaciones en los datos de salida decimos que el problema está mal condicionado.

8) Si   f   es  un  problema    que resolvemos  con un  algoritmo   g,  ¿qué    significa:
a. que g sea estable?
b. que g sea estable hacia atrás?
c. que g sea inestable?

9) ¿Qué ventaja(s) se tiene(n) al calcular un error hacia atrás vs calcular un  error hacia delante?

## 2.1
1) ¿Qué factores han influido en que desde el 2002-2003 a la fecha, el performance de los procesadores se esté incrementando en un 20% por año vs el 50% de incremento por año que se tenía entre 1986 y 2002?

Se llegó a límites físicos en cuanto a consumo de energía y disipación de calor, conforme a que la rapidez de los procesadores aumenta, la energía que recorre los chips también es mayor.

2) Menciona los componentes y realiza un esquema de  una arquitectura von 
Neumann y descríbelas.



3) Menciona algunas de  las tareas  de  un  sistema operativo.

- Maneja los recursos del hardware y software en la computadora.
- Determina qué programas pueden y cuando pueden correr.
- COntrola el alojamiento de memoria para los programas que corren.
- Controla el acceso a devises como los discos duros y las tarjetas de interfaz de red
- Crea procesos al momento en el que un usuario corre un programa.

4) ¿Qué es  un  proceso y   de  qué consta?

Un proceso es una isntancia de un programa que se ejecuta en el procesador y consta de:

- EL ejecutable en lenguaje de máquina.
- Un bloque de memoria que incluye el código del ejecutable, un stack que mantiene un seguimento de las funcionaes activas, un heap y otras ubicaciones de memoria.
- Un file descriptor para una desprición de los recursos que están alojados para el proceso.
- Información sobre los recursos del hardware y software que el proceso puede acceder.
- Información sobre el estado del proceso tal como el contenido de los reisters, memoria del proceso y si el proceso está correindo o espera algún recurso.

5) ¿Qué es  un thread?

Un thread al igual que un proceso, es una instancia de un programa que se ejecuta en un procesador con la característica de estar contenido en un proceso. Así, puede usar el mismo ejecutable, la misma memoria y los mismos dispositivos de input/output, pero distinto stack y program counter, por ellos los threads son considerados proceso "light weight".

6) ¿Qué es  el  threading?  ¿qué    ventajas    nos da  para    la  programación    en  un  sistema de memoria compartida?

El threading es cuando un proceso inicia un thread que "forks off" del mismo y luego cuando el thread termina su labor, "joins" al proceso de nuevo. Las ventajas que da:

- El cambio entre threads en muchos sistemas es más rápido que el cambio entre procesos.
- El threading les otorga a los programadores un mecanismo para dividir las tareas en una forma más o menos independiente, con la propiedad de que si un thread está bloqueado, otro thread puede correr, cada uno con su propio program counter y su propio stack.

El threading, permite que los threads compartan ubicaciones de memoria, pues comparten recursos del proceso. Los procesos tienen memorias privadas, es decir, un proceso no puede acceder a la memoria de otro.
-

7) ¿Qué es  el  cache?

El cache es una colección de ubicaciones de memoria que pueden ser accesadas en menor tiempo que otras ubicaciones de memoria.

8) Nosotros como    programadores   o   programadoras,  ¿cómo   podemos obtener 
ventajas    del cache?

Al tener un conocimiento de como se maneja la memoria cache, es posible acomodar las instrucciones de modo que la cantidad de cache misses sea la menor posible. Esto hará más rápida la ejecución ya que el acceso a la memoria cache es más veloz.

9) ¿Qué es  un  cache   hit?    ¿un cache   miss?

Cuando el CPU intenta accesar datos, el primer lugar donde lo intenta es la memoria caché. Si el dato se encuentra ahí se conoce como cache hit, si el dato no se encuentra es un cache miss.

10) De  acuerdo a   la  taxonomía   de  Flynn,  ¿qué    tipos   de  arquitecturas   existen?    
Menciona    sus características,    ventajas    /desventajas    y   ejemplos.

-SISD
  - Single Instruction Single Data
  - Ejecutan una instrucción y leen o almacenan un data item en un tiempo determinado
  - Característico en computadoras con un procesador.
  - Es un sistema Von Neumann clásico, un stream de instrucciones procesan un solo stream de datos en un tiempo determinado.
-SISM
  - Single instruction multiple data.
  - Operan en múltiples stream de datos al ejecutar la misma instrucción en múltiplos data items.
  - Un stream de instrucciones son transmitidas concurrentemente a múltiples procesadores, cada uno con su propio stream de datos.
  - Como ventaja es ideal para dividir instrucciones que involucran datos de forma independiente entre las unidades de procesamiento.
  - Desventaja es que al restricción de que cada unidad de procesamiento debe recibir una sola instrucción en un tiempo determinado condice a casos en los que una unidad de procesamiento esté "idle", degradando así el performance total.
  - Ejemplos de esta arquitectura son el Vector o Array Procesor y los GPU.

-MIMD

- Multiple Instruction Multiple Data
- Estos sistemas permiten la ejecución simultanea de múltiples streams de instrucciones en múltiples streams de datos.
- Típicamente consisten de una colección independiente de cores. Así, ejecutan sus propios streams de instrucciones en sus propios strams de datos.
- Los sistemas MIMD son asíncronos, cada procesador trabaja a su propio ritmo.
- De acuerdo a la organización de la memoria estos sistemas se pueden organizar en: Shared memory systems (Symetric multiprocessors,NUMA systems), Distributed memory systems, donde la comunicación ocurre a través del network y message passing, por ejemplo Clusters (nodos con Shared memory systems (lo que lo hace un hybrid system)), Grids (nodos heterogeneos con ubicaciones geográficas distintas), Massively parallel processors, por ejemplo la GPU.


-MIMD

-SIMT

11) Menciona    algunas características y   ejemplos    de:
a. sistemas de  memoria distribuida.
b. sistemas de  memoria compartida.

Shared memory systems (Symetric multiprocessors,NUMA systems)


Distributed memory systems, donde la comunicación ocurre a través del network y message passing, por ejemplo Clusters (nodos con Shared memory systems (lo que lo hace un hybrid system)), Grids (nodos heterogeneos con ubicaciones geográficas distintas), Massively parallel processors, por ejemplo la GPU.


12) ¿Qué significan los términos concurrencia, paralelo, distribuido?

La concurrencia es cuando existen múltiples tasks que pueden estar en progreso en cualquier instante, por ejemplo un Sistema Operativo. Tanto los programas en paralelo como los distribuidos ejecutan múltiples tasks simulténeamente en cores distintos. Los paralelos usualemnte están conectados cerca uno del otro y comparten memoria o bien están conectados por una network de alta velocidad. Por otro lado los distribuidos son usualemnte "loosely coupled" y pueden estar a kilómetros de distancia.

13) ¿Cuáles son los enfoques    que se  utilizan    para    escribir    programas   en  paralelo?

Los enfoques más comunes son:

-Paralelización de tareas entre los cores
-Paralelización de los datows entre los cores

14) Define a    cuál enfoque    corresponde (de acuerdo a   la  pregunta    13) cada    uno de  los 
siguientes  incisos:

a)  Supón   que tienes  2   cores   y   un  arreglo de  tamaño  100
if(rango_core   módulo  2   ==  0   )
operar  en  los elementos   50  a   99
else
operar  en  los elementos   0   a   49
Donde   módulo  es  una operación   que nos devuelve    el  residuo al  dividir un  número  
entre   otro.

b) Tenemos  tres    trabajadores:   Aurora, Pedro,  Daniel
if(mi_nombre    es  Pedro)
lavo    el  baño
else
voy de  compras

15) En el cómputo en paralelo debemos realizar coordinación entre procesos o threads y considerar el load balancing. Menciona tipos de coordinación que existen y ¿a qué se refiere el load balancing?

## 2.2

1) ¿Qué significan  las siglas  MPI?
2) Detalla  qué es  MPI.
3) ¿Es  posible usar    MPI en  un  sistema de  memoria compartida?
4) ¿Qué es  un  código SPMD?
5) ¿A   qué se  le  llama   no  determinismo    y   da un   ejemplo en  el  que esto    surge en    un  
sistema de  memoria distribuida?
6) Menciona algunos problemas   que pueden  surgir  en  MPI en  cuanto  al  uso de  las 
funciones   send    y   receive.
7) ¿Cuáles  son los pasos   a   seguir, que de  acuerdo a   Ian Foster, un@ puede   seguir  
para    el  diseño  de  programas   en  paralelo?

## 2.3 y   2.4

1) ¿Qué ventaja en  cuanto  a   coordinación    entre   los cores (o    procesadores),  tiene   un  
sistema de  memoria compartida  vs  un  sistema de  memoria distribuida?    
2) ¿Qué significa   la  "P" de  Pthreads?
3) ¿Qué modelo  de  programación    se  utiliza en  Pthreads y  en  openMP?
4) ¿Qué significa   la  "MP"    de  openMP?
5) ¿Qué es  un  team    en  openMP?
6) Menciona las ventajas    y   desventajas de  usar    Pthreads    vs  openMP
7) ¿Qué es  un  pragma  en  C?
8) ¿Qué es  una critical    section?    ¿Qué    es  un  race    condition? ¿Qué opciones    se  
mencionaron en  clase   para    lidiar con esto en Pthreads? ¿en openMP?
9) ¿Qué es  el  scope de    variables?, en  openMP  ¿cuál   es  la  terminología    usada   para    
nombrar a   las variables   que pueden ser  accesadas por   todos   los threads?

## 2.5

1) ¿Qué significan  las siglas  GPU?
2) ¿Qué factores    han determinado un  mejor   performance de  una GPU vs  una CPU?
(contrasta  los diseños de  una CPU vs  una GPU).
3) ¿Qué significa   que una GPU sea general purpose?
4) ¿Qué significan  las siglas  CUDA?
5) Detalla  qué es  CUDA.
6) ¿Qué es  y   en  qué consiste    CUDA    C?
7) ¿Qué diferencia(s) existe(n) entre   un  cuda-thread y   un  cpu-thread?
8) Considerando la  arquitectura    de  una GPU:
a. Realiza  un  esquema de  una streaming   multiprocessor (SM).
b. ¿De  qué está    compuesto   un building block?
c. ¿Qué recursos    son compartidos por los bloques de  cuda-threads    que se
asignan a   una SM?
9) Considerando CUDA    C:
a. ¿Qué es  un  kernel?
b. ¿Qué es  un  grid?
c. ¿Cuál es el  número  máximo  de bloques  de  cuda-threads    que pueden  ser 
lanzados    por cada    dimensión   de un   grid    en  un  kernel?
d. ¿Quién asigna    los bloques de  cuda-threads    a   las SM’s?
e. ¿Qué características tienen  los bloques de  cuda-threads que    se  asignan una
SM?
f. ¿Qué es  un  warp?
10) Menciona    las diferentes  CUDA-memories   que existen en  las GPU's y da  
características de  ellas.