---
title: "Tarea 4"
author: "Daniel Sharp"
date: "March 7, 2018"
output: 
  html_document:
    keep_md: true
---
## Ejercicio 1:  

### a) Modifica la función longitud_string del siguiente programa siguiendo estos dos pasos:  
Los cambios solicitados se encuentran especificados dentro del código:  

```{bash}
cat ejercicio_1a.c
```  
Resultado:
```{bash}
gcc ejercicio_1a.c
./a.out
```   
### b) Investiga el uso de la función scanf para que imprima la longitud de los strings del archivo.txt:
```{bash}
cat ejercicio_1b.c
```  
Resultado:  
```{bash}
gcc ejercicio_1b.c
./a.out < archivo.txt
```

## Ejercicio 2  

### a) Modifica el programa para que imprima sólo aquellas líneas que tienen más de 80 caracteres.  
```{bash}
cat ejercicio_2a.c
```  
Resultado:  
```{bash}
gcc ejercicio_2a.c
./a.out < archivo2.txt
```  
Hay dos líneas con más de 80 caracteres.  

### b) Modifica el programa para que quite los espacios de cada línea leída.
```{bash}
cat ejercicio_2b.c
```  
Resultado:  
```{bash}
gcc ejercicio_2b.c
./a.out < archivo2.txt
```

### c) Modifica la función copia para que no use break pero todavía debe de usar el índice i.
```{bash}
cat ejercicio_2c.c
```  
Resultado:  
```{bash}
gcc ejercicio_2c.c
./a.out < archivo2.txt
```

### d) Modifica la función copia para que no use índices y sólo apuntadores.
```{bash}
cat ejercicio_2d.c
```  
Resultado:  
```{bash}
gcc ejercicio_2d.c
./a.out < archivo2.txt
```  
### e) Escribe una función voltea que reciba un string s e imprima el string s al revés. Añade esta función para que el programa lea líneas y las imprima volteadas.
```{bash}
cat ejercicio_2e.c
```  
Resultado:  
En este inciso se eliminan los caracteres especiales (guiones y apóstrofes) del texto porque provocaban problemas de encoding:  
```{bash}
gcc ejercicio_2e.c
cat archivo2.txt | tr -dc '[:alnum:]\n\r ' | ./a.out
```

### f) Qué efecto tiene escribir extern para la declaración de variables dentro de main(), getline() y copia()?  

El uso de extern tiene el objetivo de especiicar al programa que la variable que se esta declarando dentro del main, getline o copia es una variable global preexistente. Sin el extern, se inicializa una variable local que 'rompe' el programa pues no tiene un valor asignado. El extern permite que una variable definida de manera global pueda ser modificada y utilizada por muchas funciones sin que sea necesario que estas la reciban como un argumento. Además, al usar extern no le asigna memoria a la variable.  

## Ejercicio 3  

### a) La funcion corta_string no hace un chequeo si el string que recibe como parámetro debe de tener al menos un caracter. Modifica esta función de modo que haga este chequeo:  
Se modificó el código para poder evaluar fácilmente si funciona correctamente nuestro chequeo. El string que evalúa es el primer argumento que recibe en la línea de comando

```{bash}
cat ejercicio_3a.c
```  
Resultado:  
Se corre el ejemplo original:  
```{bash}
gcc ejercicio_3a.c
./a.out "Campos verdes" #Indicamos un string con más de 1 caracter
```  
Y observamos que efectivamente remueve el primer caracter. Ahora lo probamos con un solo caracter.  
```{bash}
./a.out C
```  
Efectivamente imprime correctamente el mensaje de error.  

### b) Cómo modificas la forma en que es llamada corta_string dentro de main de modo que devuelva: verdes ?? (hay un espacio antes del string "verdes").    

```{bash}
cat ejercicio_3b.c
```  
Resultado:  
```{bash}
gcc ejercicio_3b.c
./a.out
```  

## Ejercicio 4  

### a) Modifica el programa para que en lugar de inicializar el string s con un tamaño 50 sea dinámica su inicialización, es decir, que no tengas que escribir 50 o algún valor definido para el tamaño del string s.

```{bash}
cat ejercicio_4a.c
```  
Resultado:  

```{bash}
gcc ejercicio_4a.c
./a.out
```  
### b) Escribe una función voltea_string que reciba como parámetro un char\*  y devuelva un char\*  cuya operación sea devolver un string volteado

```{bash}
cat ejercicio_4b.c
```  
Resultado:  

```{bash}
gcc ejercicio_4b.c
./a.out
```

