# This is a simple standalone example. See README.txt
# See magma/make.inc for alternate BLAS and LAPACK libraries,
# or use pkg-config as described below.

# Paths where MAGMA, CUDA, and OpenBLAS are installed.
# MAGMADIR can be .. to test without installing.
MAGMADIR     ?= /media/mario/G/MAGMA/magma-2.3.0
CUDADIR      ?= /usr/local/cuda

CC            = gcc
FORT          = gfortran
LD            = gcc
CFLAGS        = -Wall
# needs -fopenmp if MAGMA was compiled with OpenMP
LDFLAGS       = -Wall #-fopenmp


# ----------------------------------------
# Flags and paths to MAGMA, CUDA, and LAPACK/BLAS
MAGMA_CFLAGS     := -DADD_ \
                    -I$(MAGMADIR)/include \
                    -I$(MAGMADIR)/sparse/include \
                    -I$(CUDADIR)/include

MAGMA_F90FLAGS   := -Dmagma_devptr_t="integer(kind=8)" \
                    -I$(MAGMADIR)/include

# may be lib instead of lib64 on some systems
MAGMA_LIBS       := -L$(MAGMADIR)/lib -lmagma_sparse -lmagma \
                    -L$(CUDADIR)/lib64 -lcublas -lcudart -lcusparse \



# ----------------------------------------
# Alternatively, using pkg-config (see README.txt):
# MAGMA_CFLAGS   := $(shell pkg-config --cflags magma)
#
# MAGMA_F90FLAGS := -Dmagma_devptr_t="integer(kind=8)" \
#                   $(shell pkg-config --cflags-only-I magma)
#
# MAGMA_LIBS     := $(shell pkg-config --libs   magma)


# ----------------------------------------
default:
	@echo "Available make targets are:"
	@echo "  make c  # compiles "
	@echo "  make clean     # deletes executables and object files"

c: qr3

clean:
	-rm -f mine *.o *.mod

.SUFFIXES:


# ----------------------------------------
# C example
%.o: %.c
	$(CC) $(CFLAGS) $(MAGMA_CFLAGS) -c -o $@ $<

mine: mine.o
	$(LD) $(LDFLAGS) -o $@ $^ $(MAGMA_LIBS)
