---
title: "MNO-Tarea5"
author: "101421"
date: "3/26/2017"
output: html_document
---

##Pregunta a: Investiga por qué se usan comillas en la línea que tiene include en main.c y en funciones.c en lugar de usar < >

El archivo .h es un archivo de encabezados que describe todos los prototipos de función y estructuras que se utilizarán en el archivo donde se incluye. 

En el caso de que esté encerrado entre **""** signifca que son librerías locales al programa que la usa. Si usamos **<>** estas definiciones son las que vienen instaladas en el directorio de librerias generales.

Usamos estas directivas para que el compilador sepa dónde buscar las liberías.

##Pregunta b: Investiga el uso de static en la definición de variables externas de funciones.c

En C, el ciclo de vida de las variables se define por su tipo de almacenamiento. Una variable estática definida fuera de una función, puede ser usada por todas las funciones dentro de ese archivo, y por eso a veces recibe el nombre de variable global.

# Adicionalmente Investigar:

1. ##dgemm: 
Es una rutina para multiplicación de matrices de doble precisión:

   C := $\alpha$ $*$ op (A) $*$ op(B) + $\beta$ $*$ C
   
   donde op (X) es una de: op (X) = X o  op(X) = X^t^,

  $\alpha$ y ) + $\beta$ son escalares
  
  A~(m$*$k)~, B~(k$*$n)~ y C~(m$*$n)~ son matrices


2. ##BLAS: 
**Basic  Linear  Algebra  Subprograms** es  un  conjunto  de  rutinas escritos en Fortran 77 para operaciones básicas de Álgebra lineal. Estas rutinas proveen bloques estándares para realizar operaciones entre vectores y matrices.

El nivel 1 de BLAS hace operaciones básicas escalar-vector.
El nivel 2 de BLAS hace operaciones vector-matriz.
El nivel 3 de BLAS hace operaciones matriz-matriz.

3. ##LAPACK:
**Linear Algebra Package** es una librería estándard muy utilizada para Algebra Lineal numérica. Provee rutinas que resuelven sistema de ecuaciones lineales y mínimos cuadrados, problemas de eigen-valores, y descomposición en valores singulares.


4. ##ATLAS: 
**Automatically Turned Linear Algebra Software** es una implementación completa de las APIs de BLAS, asi como también trae funciones adicionales de LAPACK.

