---
title: "Untitled"
author: "Eduardo Martínez, Ariel Vallarino, Jorge Altamirano"
date: "26 de abril de 2019"
output: html_document
---

```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(purrr)
```

```{r}
k <- 1.1  # Precio strike
r <- 0.06 # tasa libre de riesgo

# t1 <- c(1.09, 1.16, 1.22, 0.93, 1.11, 0.76, 0.92, 0.88)
# t2 <- c(1.08, 1.26, 1.07, 0.97, 1.56, 0.77, 0.84, 1.22)
# t3 <- c(1.34, 1.54, 1.03, 0.92, 1.52, 0.9, 1.01, 1.34)
# precios <- matrix(c(t1, t2, t3), ncol = 3)

set.seed(123456)
# precios <- matrix(rexp(300, 1), ncol = 3)
# precios <- matrix(rexp(180 * 10000, 1), ncol = 180)
precios <- matrix(exp(rnorm(180 * 10000)), ncol = 180)
```


```{r}
payoff_call <- function(x,k){
  (x-k + abs(x-k))/2
}

payoff_put <- function(x,k){
  (k-x + abs(k-x))/2
}
```


```{r}
payoffs <- data.frame(sim=1:nrow(precios), apply(precios, MARGIN = c(1,2), k=k, FUN = payoff_put)) 

colnames(payoffs) <- c("sim", paste(rep("p",ncol(payoffs)-1), c(2:ncol(payoffs)-1), sep=""))

payoffs
```


```{r}
precios <- data.frame(sim=1:nrow(payoffs), precios) 

precios
```


```{r}
terminos <- 100
ceros <- 0
for (i in (ncol(precios)-1):2){
  ids_precio <- c("sim", paste0("X", i-1))
  ids_payoffs <- c(paste0("p", i-1), paste0("p", i))

  payoff_tmp <- data.frame(precios[ids_precio], payoffs[ids_payoffs]) %>% 
    mutate(vp = exp(-r) * .[[ncol(.)]]) %>% 
    filter(.[ids_payoffs[1]] > 0)
  
  terminos <- c(terminos, nrow(payoff_tmp))
    
  # formula <-  paste0("vp ~ ", ids_precio[2], " + I(" , ids_precio[2], "^2)")
  # formula <-  paste0("vp ~ ", "I(1-", ids_precio[2], ")", " + I(0.5*(" , ids_precio[2],"^2 -4*", ids_precio[2], "+2))")
  # formula <-  paste0("vp ~ ", ids_precio[2], " + I(" , ids_precio[2], "^2)+I(",ids_precio[2],"^3)+I(",ids_precio[2],"^4)+I(",ids_precio[2],"^5)+I(",ids_precio[2],"^6)")
  formula <-  paste0("vp ~ ", ids_precio[2], " + I(" , ids_precio[2], "^2) + I(",ids_precio[2],"^3)")
  
  modelin <- lm(as.formula(formula) , data = payoff_tmp)
  
  vp_gorro <- predict(modelin, data = payoff_tmp)
  
  ids_y <- payoff_tmp %>% mutate(vp_gorro = vp_gorro) %>% 
      mutate(y = if_else(.[ids_payoffs[1]] > vp_gorro, 1,0)) %>% 
      filter(y == 0) %>% 
      select(sim) %>% 
      flatten_dbl()
  
  ceros <- c(ceros, length(ids_y))

  payoffs[ids_y, ids_payoffs[1]] <- 0
  
} 

hist(terminos)
hist(ceros)
print(payoffs)
```



```{r}
estrategias <- function(m, r){
  # Para cada fila obtengo el indice del 1er. valor > 0, si el registro contiene todos 0's retorna 0:
  ids <- unlist(lapply(apply(m[,-1], 1, function(x) which(x>0)), function(l) ifelse(length(l)>0, l[[1]],0) ))
  # Genero lista de la cantidad de registros:
  pos <- m[,1]
  # Armo matriz con Posición + ID ibtenido en el 1er. paso facilitar el recorrido de los datos:
  ids_m <- data.frame(sim=pos, ids=ids)
  # Recorro la matriz original y para cada pos. tomo el valor del ID y calculo el precio:
  vps <- matrix(unlist(lapply(pos, function(i) ifelse(ids_m[i,2] > 0, m[ids_m[i,1], ids_m[i,2]+1] * exp(-1*ids_m[i,2]*r), 0))))
  # Retorno matrix con: Posición, ID, VP: 
  ids_m <-  as.data.frame(cbind(ids_m, vps))
  return(ids_m)
}
```

```{r}
precio_final <- estrategias(payoffs, r)

hist(precio_final$ids)

```

