# Tarea 6

## Investiga sobre la subrutina de Fortran dgemv (parámetros que recibe y la salida).

DGEMM ejecuta operaciones matrix-matrix

SUBROUTINE DGEMV ( TRANS, M, N, ALPHA, A, LDA, X, INCX, BETA, Y, INCY )
.. Scalar Arguments ..
DOUBLE PRECISION   ALPHA, BETA
INTEGER            INCX, INCY, LDA, M, N
CHARACTER*1        TRANS
.. Array Arguments ..
DOUBLE PRECISION   A( LDA, * ), X( * ), Y( * )
..


Purpose
=======
DGEMV  performs one of the matrix-vector operations
y := alpha*A*x + beta*y,   or   y := alpha*A'*x + beta*y, where alpha and beta are scalars, x and y are vectors and A is an m by n matrix.



## En la carpeta analisis-numerico-computo-cientifico/C/BLAS/ejemplos/level2/ ejecuta el programa dgemv_mult_mat_vec.c y realiza pruebas con diferentes matrices y vectores definidos por ti.

Se ejecutó la siguiente prueba:

    matriz 1:
    matriz[0][0]=19.00000   matriz[0][1]=12.00000
    matriz[1][0]=20.00000   matriz[1][1]=-7.00000
    matriz[2][0]=-6.00000   matriz[2][1]=6.00000
    ------------
    vector :
    vector[0]=4.00000
    vector[1]=10.00000
    ------------
    vector resultado:
    vector[0]=196.00000
    vector[1]=10.00000
    vector[2]=36.00000


## Haz un programa que utilice la subrutina dger de Fortran.

ver dger_ejem.C

## Después de haber estudiado y entendido los archivos de definiciones.h y funciones.c y realizado los puntos anteriores y la tarea 5 responde: ¿cómo fue que pudimos llamar a las rutinas de Fortran (que almacena en una forma column-major order los arreglos de dos dimensiones) para operaciones con arreglos 2-dimensionales sin haber instalado CBLAS, si en clase se dijo que almacenar arreglos de dos dimensiones en C es en un row-major order?

Porque se descompuso la multiplicación a operaciones de vectores.

## Investiga sobre la subrutina de Fortran dgemm (parámeitros que recibe y la salida).


SYNOPSIS
SUBROUTINE DGEMM ( TRANSA, TRANSB, M, N, K, ALPHA, A, LDA, B, LDB, BETA, C, LDC )

CHARACTER*1  TRANSA, TRANSB
INTEGER      M, N, K, LDA, LDB, LDC
DOUBLE       PRECISION ALPHA, BETA
DOUBLE       PRECISION A( LDA, * ), B( LDB, * ), C( LDC, * )

Purpose
=======
DGEMM  performs one of the matrix-matrix operations

C := alpha*op( A )*op( B ) + beta*C,

where  op( X ) is one of op( X ) = X   or   op( X ) = X**T,
     alpha and beta are scalars, and A, B and C are matrices, with op( A )
      an m by k matrix,  op( B )  a  k by n matrix and  C an m by n matrix.


## En la carpeta analisis-numerico-computo-cientifico/C/BLAS/ejemplos/level3/ ejecuta el programa dgemm_mult_mat.c y realiza pruebas con diferentes matrices definidas por ti.


## En la carpeta del punto anterior encuentras la sección Multiplicación matriz-matriz con trick. Ejecuta el programa de esta sección con diferentes matrices definidas por ti y resuelve la pregunta ¿por qué funciona este trick?.

La rutina de Fortrand invierte las columnas. 

## Haz un programa que utilice la subrutina dsymm de Fortran.

ver dsymm_ejem.C
