---
title: "Tarea 5"
author: "Fernando Briseño 171349"
date: "March 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Pregunta 1
Estudia y entiende los archivos definiciones.h y funciones.c de ahí, en particular investiga por qué se usan "" en la línea que tiene #include en funciones.c en lugar de usar < >. 

**Porque ponerlo entre comillas hace que la función se busque de primero como nombre de archivo, si no lo logra, entonces procede a buscar como si se utilizaran <> que puede referirse a un encabezado.**

Investiga el uso de static en la definición de variables externas de funciones.c .

**Se usa cuando se requiere mantener un estado entre llamados a la función y no se quieren usar variables globales. Es usado para guardar una variable en la memoria asignada estáticamente en lugar de la que se asigna automáticamente. Aunque el lenguaje no dicta la implementación de estos dos tipos, la memoria estática, generalmente está reservada en sel semento de datos del programa al momento de compilarlo. **

# Pregunta 2

Investiga* sobre BLAS, CBLAS, LAPACK, ATLAS y las operaciones de nivel 1, nivel 2 y nivel 3 de BLAS y reporta sobre esta investigación que realizas. Es una investigación que contiene principalmente una descripción sobre los paquetes y niveles anteriores.

## BLAS

**Es una especificación que define un conjunto de rutinas de bajo nivel para realizar operaciones comunes de álgebra lineal tales como la suma de vectores, multiplicación escalar, producto escalar combinaciones lineales y multiplicación de matrices. Aunque la especificación de BLAS es general, las implementaciones particulares están a menudo optimizadas para conseguir mayor aceleración en una máquina o arquitectura particular, de forma que su uso puede conllevar un incremento sustancial del rendimiento. Las implementaciones de BLAS se pueden aprovechar de la existencia de hardware especial de punto flotante, tales como registros vectoriales o instrucciones SIMD.**

## CBLAS

**En lugar de llamar a las rutinas de BLAS desde un programa en C, se puede usar la interfaz CBLAS.**

## LAPACK

**LAPACK (Linear Algebra Package) es una librería estándar para algebra lineal numérica. Provee rutinas para resolver sistemas de ecuaciones lineales y mínimos cuadrados lineales, problemas de eigenvalores, y descomposición en valores singulares. Incluye rutinas para implementar la factorización de matrices en LU, QR, Cholesky y Schur. EStá escrito en FORTRAN 90, y las rutinas pueden trabajar con matrices reales y complejas tanto con precisión sencilla y doble.**

## ATLAS

**ATLAS (Automatically Tuned Linear Algebra Software) da una implementación de las API's de BLAS para C y FORTRAN 77, así como algunas funciones adicionales de LAPACK.**

## Niveles de BLAS

### Nivel 1

**Este nivel contiene todas las rutinas descritas en la presentación de BLAS de 1979, incluyendo solo operaciones vectoriales en strided arrays, productos punto, normas vectoriales, adicion de vectores y otras operaciones. **

### Nivel 2

**Este nivel contiene operaciones matriz-vector que incluyen una versión generalizada de la multiplicación matriz-vector y un solver para x en la ecuación $Tx=Y$**

### Nivel 3

**Contiene operaciones de multiplicación matriz-matriz**

# Pregunta 3

En la carpeta analisis-numerico-computo-cientifico/C/BLAS/ejemplos/level1/ ejecuta el programa dot_product.c y realiza pruebas con diferentes vectores definidos por ti.

Primero corremos el original

```{}
ffbris@ffbrisDS ~/Desktop/MNO_tarea_5 $ ./programa.out 3
------------
vector :
vector[0]=1.00000
vector[1]=0.00000
vector[2]=-3.00000
------------
vector :
vector[0]=5.00000
vector[1]=8.00000
vector[2]=9.00000
------------
resultado: -22.000000
```

Probemos con otras tres especificaciones:

Se elimina el tercer elemento del vector 1. El programa lo sustituye por cero.

```{}
ffbris@ffbrisDS ~/Desktop/MNO_tarea_5 $ ./programa.out 3
------------
vector :
vector[0]=1.00000
vector[1]=0.00000
vector[2]=0.00000
------------
vector :
vector[0]=5.00000
vector[1]=8.00000
vector[2]=9.00000
------------
resultado: 5.000000

```

Ahora se agregaron dos elementos al primer vector, para ser de cinco. Sin embargo el programa lo trunca en 3.

```{}
ffbris@ffbrisDS ~/Desktop/MNO_tarea_5 $ ./programa.out 3
------------
vector :
vector[0]=1.00000
vector[1]=0.00000
vector[2]=-99999.00000
------------
vector :
vector[0]=5.00000
vector[1]=8.00000
vector[2]=9.00000
------------
resultado: -899986.000000
```

Ahora veamos cómo se comporta con números pequeños.

Vector 1 =

.0000000000000000001

-.0000000000000000001

.0000000000000000001

Vector 2 =

.00000000000005

-.00000000000008

.000000000000009

```{}
ffbris@ffbrisDS ~/Desktop/MNO_tarea_5 $ ./programa.out 3
------------
vector :
vector[0]=0.00000
vector[1]=-0.00000
vector[2]=0.00000
------------
vector :
vector[0]=0.00000
vector[1]=-0.00000
vector[2]=0.00000
------------
resultado: 0.000000
```

# Pregunta 4

Investiga* sobre la subrutina de Fortran ddot (parámetros que recibe y la salida).

**DDOT forms the dot product of two vectors. uses unrolled loops for increments equal to one.**
    
**N	es entero, que es el número de elementos en los vectores de entrada**
**DX es un arreglo de doble precisión, de dimensión  ( 1 + ( N - 1 )*abs( INCX ) )**
**INCX	es entero, que es el espacio de memoria entre elementos de DX**
**DY es un arreglo de doble precisión, de dimensión  ( 1 + ( N - 1 )*abs( INCY ) )**
**INCY es entero, que es el espacio de memoria entre elementos de DY**

**La salida es el escalar guardado en dtemp, como podemos ver en la parte final de la rutina de FORTRAN.**

```{}
 *     .. Intrinsic Functions ..
       INTRINSIC mod
 *     ..
       ddot = 0.0d0
       dtemp = 0.0d0
       IF (n.LE.0) RETURN
       IF (incx.EQ.1 .AND. incy.EQ.1) THEN
 *
 *        code for both increments equal to 1
 *
 *
 *        clean-up loop
 *
          m = mod(n,5)
          IF (m.NE.0) THEN
             DO i = 1,m
                dtemp = dtemp + dx(i)*dy(i)
             END DO
             IF (n.LT.5) THEN
                ddot=dtemp
             RETURN
             END IF
          END IF
          mp1 = m + 1
          DO i = mp1,n,5
           dtemp = dtemp + dx(i)*dy(i) + dx(i+1)*dy(i+1) +
      $            dx(i+2)*dy(i+2) + dx(i+3)*dy(i+3) + dx(i+4)*dy(i+4)
          END DO
       ELSE
 *
 *        code for unequal increments or equal increments
 *          not equal to 1
 *
          ix = 1
          iy = 1
          IF (incx.LT.0) ix = (-n+1)*incx + 1
          IF (incy.LT.0) iy = (-n+1)*incy + 1
          DO i = 1,n
             dtemp = dtemp + dx(ix)*dy(iy)
             ix = ix + incx
             iy = iy + incy
          END DO
       END IF
       ddot = dtemp
       RETURN
```


# Pregunta 5

Haz un programa que utilice la subrutina daxpy de Fortran.

Resultado:

```{}
ffbris@ffbrisDS ~/Desktop/MNO_tarea_5 $ ./programa.out 3
------------
escalar : 9.000000 
vector :
vector[0]=1.00000
vector[1]=-3.00000
vector[2]=5.00000
------------
vector :
vector[0]=8.00000
vector[1]=10.00000
vector[2]=-1.00000
------------
RESULTADO:
vector[0]=17.00000
vector[1]=-17.00000
vector[2]=44.00000

```


