/*************************************************************************
# ITAM
## Maestría en Ciencia de Datos
## Tarea 04 Ejercicio 2
### Metódos Numéricos y Optimización
#### Profesor: Erick Palacios
#### Alumna: Gabriela Flores Bracamontes - 160124
Instrucciones:
a) Modifica el programa para que imprima sólo aquellas líneas que tienen más de 80 caracteres.
b) Modifica el programa para que quite los espacios de cada línea leída.
c) Modifica la función copia para que no use break pero todavía debe de usar el índice i.
d) Modifica la función copia para que no use índices y sólo apuntadores.
e) Escribe una función voltea que reciba un string s e imprima el string s al revés. Añade esta función para que el programa lea líneas y las imprima volteadas.
f) Qué efecto tiene escribir extern para la declaración de variables dentro de main(), getline() y copia()?
************************************************************************/

"Extern" es una palabra reservada utilizada para indicarle al compilador que el dominio de 
la función ó la variable está disponible en otro lugar, ya sea al inicio del archivo o en algún otro.

Hay una diferencia entre "extern" en las funciones y en las variables: 
* En las variables no instancia la propia variable, es decir, no asigna ninguna memoria. Esto tiene que hacerse en otro lugar. Por lo tanto, es importante si desea importar la variable desde otro lugar. 
* Para las funciones, esto sólo indica al compilador que el enlace es externo. Como este es el valor predeterminado (se utiliza la palabra clave "estática" para indicar que una función no está vinculada mediante vinculación externa) no es necesario utilizarlo explícitamente.

Bibliografía
* http://stackoverflow.com/questions/496448/how-to-correctly-use-the-extern-keyword-in-c
* https://es.wikipedia.org/wiki/Variable_externa
* http://www.geeksforgeeks.org/understanding-extern-keyword-in-c/
