---
title: 'MNO: Tarea 5'
output:
  pdf_document: default
  pdf_notebook: default
---

# Pregunta 1

Estudia y entiende los archivos definiciones.h y funciones.c de ahí, en particular investiga por qué se usan "" en la línea que tiene #include en funciones.c en lugar de usar < >. Investiga el uso de static en la definición de variables externas de funciones.c .

## R.

definiciones.h y funciones.h sirven para inicializar y llenar valores en un vector o matriz dado un archivo externo.
La diferencua entre usar < > o "" al llamar un programa en el header es que al usar < > se busca el archivo en un path específico mientras que al usar " " se busca el archivo en el mismo directorio del programa.
Las variables deinidas como static tienen la particularidad de que "sobreviven" cuando se acaba de ejecutar el programa o función en la que viven.

# Pregunta 2

Investiga* sobre BLAS, CBLAS, LAPACK, ATLAS y las operaciones de nivel 1, nivel 2 y nivel 3 de BLAS y reporta sobre esta investigación que realizas. Es una investigación que contiene principalmente una descripción sobre los paquetes y niveles anteriores.

## R.-

### BLAS
BLAS (Basic Linear Algebra Subprograms) es un grupo de rutinas que permiten realizar operaciones algebraicas básicas. Este tipo de rutinas se dividen en 3 niveles los cuales son:
Nivel 1.- Operaciones vector-vector (normas, productos punto, multiplicaciones, etc.)
Nivel 2.- Operaciones matriz-vector (multiplicaciones, resolver matrices triangulares, etc.)
Nivel 3.- Operaciones matriz- matriz (rankeo, multiplicacion, resolución de matrices, etc.)
BLAS se utiliza como base para el desarrolo de rutinas más avanzadas como LAPACK.
CBLAS es la implementación en C de BLAS.

### LAPACK
LAPACK es una paquetería para realizar operaciones algebraicas de alto nivel, tales como resolver sistemas de ecuaciones simultanios, problemas de eigevalores, factorización matricial,etc.
LAPACK usa BLAS como base.

### ATLAS
ATLAS o Automatically Tuned Linear Algebra es un proyecto que se encuentra actualmente en desarrollo. Este pretende proveer un sodtware de algebra lineal portable. Usa como base BLAS y algunas cosas de ATLAS.


# Pregunta 3

Se definieron nuevas V1 y V2
El output fue:
./programa.out 8

vector :
vector[0]=53.00000
vector[1]=65.00000
vector[2]=144.00000
vector[3]=30.00000
vector[4]=-333.00000
vector[5]=4.00000
vector[6]=34.00000
vector[7]=234.00000

vector :
vector[0]=45.00000
vector[1]=38.00000
vector[2]=542.00000
vector[3]=-234.00000
vector[4]=23.00000
vector[5]=-34.00000
vector[6]=0.00000
vector[7]=0.00000

resultado: 68088.000000


# Pregunta 4 
Investiga* sobre la subrutina de Fortran ddot (parámetros que recibe y la salida).

## R.

ddot recibe:
N: tamaño de vector
DX: Vector X
INCX: espacio del vector x en memoria
DY: Vector Y
INCY: espacio del vector y en memoria

Da el producto punto entre el vector x y el vextor y

# Pregunta 5
Salida del programa mult_escalar.c

programa1.out 8

vector :
vector[0]=53.00000
vector[1]=65.00000
vector[2]=144.00000
vector[3]=30.00000
vector[4]=-333.00000
vector[5]=4.00000
vector[6]=34.00000
vector[7]=234.00000

vector :
vector[0]=45.00000
vector[1]=38.00000
vector[2]=542.00000
vector[3]=-234.00000
vector[4]=23.00000
vector[5]=-34.00000
vector[6]=0.00000
vector[7]=0.00000

resultado: 468.000000
