# Tarea 5 
## 114535

### Estudia y entiende los archivos definiciones.h y funciones.c de ahí, en particular investiga por qué se usan "" en la línea que tiene #include en funciones.c en lugar de usar < >. Investiga el uso de static en la definición de variables externas de funciones.c .

#### Diferencia entre <> y ""
La diferencia radica en la ubicación donde el procesador buscará el archivo en la lista estandar de directorios.

En el caso de #include<filename> y en el de #include"filename" el procesador busca primero en el mismo directorio del archivo que se esté ejecutando y posteriormente con el método <>

#### Uso de static en la definición de variables externas.
Una variable estática global definida fuera de una función puede mantener su valor y ser accesible dentro del script, siendo privada para otros archivos de c.

En el caso de la variable estática dentro de una función va a mantener su valor en cada invocación que se le haga a la función. Esto suele usarse para seguir estados de invocación de la misma función.


### Investiga. sobre BLAS, CBLAS, LAPACK, ATLAS y las operaciones de nivel 1, nivel 2 y nivel 3 de BLAS y reporta sobre esta investigación que realizas. Es una investigación que contiene principalmente una descripción sobre los paquetes y niveles anteriores.
BLAS: Basic Linear Algebra Subprograms, conjunto de rutinas (low-level) que proveen rutinas estandarizadas con las que se puede construir scripts más complejos, está enfocado en ejecutar operaciones de matrices y vectores. 

El nivel 1 de Blas realiza operaciones por escalares y operaciones vector-vector.
Algunas funciones en este nivel son: copy (copy vector), dot (dot product), scal (vector-scalar product)
El nivel 2 realiza operaciones matriz-vector 
Algunas funciones de este nivel son: hpmv (Matrix-vector product using a Hermitian packed matrix), tpsv (Solution of a linear system of equations with a triangular packed matrix)

El nivel 3 realiza operaciones del tipo matriz-matriz
Algunas funciones de este nivel son: herk (Performs a Hermitian rank-k update.)

CBLAS: Intefaz en C para BLAS
LAPACK: Colección de high-level operaciones de álgebra lineal construido sobre BLAS en código Fortran 77
ATLAS: The Automatically Tuned Linear Algebra System es una implementación de BLAS comunmente utilizada en linux.

Biblio: 
- https://www.seehuhn.de/pages/linear
- https://software.intel.com/en-us/mkl-developer-reference-fortran-blas-level-1-routines-and-functions

### En la carpeta analisis-numerico-computo-cientifico/C/BLAS/ejemplos/level1/ ejecuta el programa dot_product.c y realiza pruebas con diferentes vectores definidos por ti.


### Investiga sobre la subrutina de Fortran ddot (parámetros que recibe y la salida).

ddot()

    DDOT genera el producto punto de dos vectores.

double precision function ddot	(	integer                      	N,
                                    double precision, dimension(*) 	DX,
                                    integer 	                    INCX,
                                    double precision, dimension(*) 	DY,
                                    integer 	                    INCY 
                                    )	
Bibliografía:
- http://www.netlib.org/lapack/explore-html/de/da4/group__double__blas__level1_ga75066c4825cb6ff1c8ec4403ef8c843a.html#ga75066c4825cb6ff1c8ec4403ef8c843a

