---
title: "Ordenamiento de elementos en un arreglo"
author:
  - Elizabeth Solis
  - Daniel Sharp
  - Christian Challu
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```
\newpage

\tableofcontents

\newpage
\section{Introducción}

\subsection{Deficinición de arreglo}

Un arreglo es un conjunto de datos homogéneos; es decir, los datos que almacena son del 
mismo tipo. Dichos datos tienen una localización de forma consecutiva en la memoria RAM 
y podemos acceder a ellos a través de su posición. En general, la dimensión del arreglo 
se define con el arreglo y no se puede incrementar de manera dinámica.


\subsection{Tipos de arreglos}

Con base en la dimensión del arreglo se puede clasificar de la siguiente manera  

- Unidimensional: Es una colección finita y ordenada del mismo tipo de datos; es la estructura 
natural de una lista que contiene los mismos elementos.  
Se almacenan bajo el mismo nombre y la manera en la cual se puede obtener cierto elemento 
es através de su posición. Para declarar el arreglo se debe definir el tipo, nombre y su 
dimensión. En este caso la dimensión es de $n \text{x}1$.

- Multidimensional: Es un tipo de dato estructurado con más de una dimensión por lo que 
para acceder a un elemento se debe tener un índice para cada dimensión asociada.

\subsection{Ordenación de elementos de un arreglo}

Una de las principales operaciones en los arreglos es el ordenamiento de elementos debido a 
que es más rápido acceder a los datos de un arreglo ordenado que uno que no está ordenado, lo 
cual se traduce en eficiencia. 

Existen diversos algoritmos para ordenar los elementos de un arreglo que se mencionarán con 
mayor detalle en la siguiente sección.

\newpage
\section{Algoritmos de ordenamiento de arreglos}

\subsection{Método de burbuja}

\subsection{Método de selección}

\subsection{Método de inserción}

Ejemplo de ordenamiento por inserción ordenando una lista de números aleatorios.
El ordenamiento por inserción (insertion sort en inglés) es una manera muy natural de ordenar para un ser humano, y puede usarse fácilmente para ordenar un mazo de cartas numeradas en forma arbitraria. Requiere O(n²) operaciones para ordenar una lista de n elementos.

Inicialmente se tiene un solo elemento, que obviamente es un conjunto ordenado. Después, cuando hay k elementos ordenados de menor a mayor, se toma el elemento k+1 y se compara con todos los elementos ya ordenados, deteniéndose cuando se encuentra un elemento menor (todos los elementos mayores han sido desplazados una posición a la derecha) o cuando ya no se encuentran elementos (todos los elementos fueron desplazados y este es el más pequeño). En este punto se inserta el elemento k+1 debiendo desplazarse los demás elementos.

\newpage
\section{Conclusiones}


\newpage
\section{Anexo}

En esta sección se encuentran los códigos implementados.

\subsection{Código implementado para el método de ordenamiento por inserción}

```{c}
void Insercion(int numbers[], int array_size) {
  int i, a, index;
  for (i=1; i < array_size; i++) {
    index = numbers[i];
    a = i-1;
    while (a >= 0 && numbers[a] > index) {
      numbers[a + 1] = numbers[a];
      a--;
    }
    numbers[a+1] = index;
  }
}
```

\newpage
\section{Referencias}









