CC=gcc

ejercicio1: 
	$(CC) Tarea4_1.c -o ejercicio1.out

ejecuta_1: ejercicio1
	./ejercicio1.out < archivo_1.txt

ejercicio2: 
	$(CC) Tarea4_2.c -o ejercicio2.out

ejecuta_2: ejercicio2
	./ejercicio2.out < archivo.txt	

ejercicio3: 
	$(CC) Tarea4_3.c -o ejercicio3.out

ejecuta_3: ejercicio3
	./ejercicio3.out	

ejercicio4: 
	$(CC) Tarea4_4.c -o ejercicio4.out

ejecuta_4: ejercicio4
	./ejercicio4.out	

clean:
	-rm -f ejercicio1.out
	-rm -f ejercicio2.out
	-rm -f ejercicio3.out
	-rm -f ejercicio4.out