# Book settings
author: "Erick Palacios Moreno"
title: ""
logo: logo.png

repository:
  #url: https://github.com/ITAM-DS/analisis-numerico-computo-cientifico/
  url: https://github.com/palmoreck/dockerfiles-for-binder
  #branch: master
  branch: jupyterlab_optimizacion
  path_to_book: analisis-numerico-computo-cientifico/libro_optimizacion/temas/

#html:
#  use_edit_page_button: true
#  use_repository_button: true
#  use_issues_button: true

launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  thebe: true

latex:
  latex_documents:
    targetname: book.tex
