---
title: "Tarea 5"
author: "Cristian Challu"
date: "March 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Pregunta 1

Se utiliza #include "file" para archivos propios del programa. En este caso el programa busca primero el archivo en el directorio del current file y despues en el directorio usado por \<file\>. Fuente: https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html

En el archivo funciones.c se utiliza static int i,j para que estas variables solo sean visibles por en el archivo funciones.c. Otros archivos pueden accesar a esas variables si se utiliza #include "file". Fuente: https://stackoverflow.com/questions/572547/what-does-static-mean-in-c

#### Pregunta 2

##### BLAS
BLAS (Basic Linear Algebra Subprograms) son rutinas para desempeñar operaciones basicas de vectores y matrices. El NIVEL 1 realiza operaciones entre vectores o entre vectores y escalares. El NIVEL 2 realiza operaciones entre vectores y matrices. El NIVEL 3 realiza operaciones entre matrices.

##### CBLAS
CBLAS es una interfaz C-Style a las rutinas de BLAS, es una alternativa a llamar las rutinas de BLAS desde un programa.

Fuente: https://software.intel.com/en-us/mkl-linux-developer-guide-calling-lapack-blas-and-cblas-routines-from-c/c-language-environments

##### LAPACK
LAPACK, escrito en Fortran 90, son rutinas para resolver sistemas de ecuaciones lineales, minimos cuadrados, eigenvalores y de valores singulares. Provee ademas factorizaciones fe matrices como LU, Cholesky, QR, SVD y Shur). LAPACK utiliza, en la medida de lo posibe, las rutinas de BLAS del NIVEL 3.
Fuente: http://www.netlib.org/lapack/

##### ATLAS
ATLAS (Automatically Tuned Linear Algebra Software) provee interfaces, para C y Fortran77, de BLAS y algunas rutinas de LAPACK. Fuente: http://math-atlas.sourceforge.net/

#### Pregunta 3
Output en archivo out_pregunta3.txt

#### Pregunta 4
La funcion ddot (N, DX, INCX, DY, INCY) de Fortran calcula el producto punto entre dos vectores. Recibe 5 parametros:
- N: INTEGER, number of elements in input vector(s)
- DX: DOUBLE PRECISION array, dimension ( 1 + ( N - 1 )*abs( INCX ) )
- INCX: INTEGER, storage spacing between elements of DX
- DY: DOUBLE PRECISION array, dimension ( 1 + ( N - 1 )*abs( INCY ) )
- INCY: INTEGER, storage spacing between elements of DY

La funcion devuelve un double.

Fuente: http://www.netlib.org/lapack/explore-html/d5/df6/ddot_8f.html

#### Pregunta 5
Se incluye el codigo en el archivo daxpy.c. Por simplicidad se probo con los mismos vectores que para la pregunta 3. El output se encuentra en out_pregunta5.txt
